---
- name: add ansible user and user password less ssh for login 
  hosts: all
  become: true
  tasks:
          - name: add ansible user
            user:
                    name: ansible
                    state: present
                    comment: ansible user for password less login

          - name: public key  send to  remote machine
            authorized_key:
                    user: ansible
                    key: ~/.ssh/id_rsa.pub
                    state: present

          - name: for no password
            lineinfile:
                     dest: /etc/sudoers
                     state: present
                     regexp: '^ansible ALL\='
                     line: 'ansible ALL=(ALL) NOPASSWD:ALL'
                     validate: 'visudo -cf %s '
