---
- name: make directory and copy a file in created directory
  hosts: devops
  become: true
  tasks: 
        - name: make directory
          file: 
                path: /tmp/seven/
                state: directory

        - name: copy a file to created directory 
          copy:
                  scr: /tmp/two.txt
                  dest: /tmp/seven/
          delegate_to: localhost
