---
- name: count processes on local machine and remote server
  hosts: all
  become: true
  tasks:
          - name: count process on remote server
            shell: ps | wc -l
            register: remote_processes_number

          - name: print remote running processess
            debug:
                    msg: '{{ remote_processes_number.stdout }}'

          - name: count processes of local server
            local_action: shell ps | wc -l
            register: local_processes_number

          - name: print local running processes
            debug:
                    msg: '{{ local_processes_number.stdout }}'
