---

- name: install apache server
  hosts: devops
  become: yes

  tasks:
    - name: apache
      apt:
              update_cache: yes

    - name: install apache
      service:
              name: apache2
              state: started

      when: ansible_os_family == 'Debian'

