---
- name: install apache server
  hosts: all
  become: true
  tasks:
          - name: update apt package
            apt:
                    update_cache: yes

          - name: install apache
            apt:
                    name: apache2
                    state: present
