---
- name: install nginx server
  hosts: all
  become: true
  tasks:
          - name: update machine
            apt:
                   update_cache: yes

          - name: install redis server on machine
            apt:
                    name: redis
                    state: latest
          - name: start mysql
            apt:
                  name: mysql-server
                  state: latest
                    
                    
