---
- name: install nginx server
  hosts: all
  become: true
  tasks:
    - name: update machine
      apt:
        update_cache: yes

    - name: install nginx server on machine
      apt:
        name: nginx
        state: latest

    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes

