---
- name: Public key is deployed to managed hosts for Ansible
  hosts: all
  become: true
  tasks:
    - name: Ensure key is in root's ~/.ssh/authorized_keys
      authorized_key:
        user: sudo
        state: present
        key: '{{ lookup("file", "~/.ssh/id_rsa.pub") }}'

